baseurl: /edb-test
permalink: pretty
markdown: rdiscount
prose:
  siteurl: 'http://prose.io/#mklarmann/edb-test/'
  ignore:
    # - _prose.yml
  metadata:
    _edb:
      - name: "foo"
	    field:
		  element: "hidden"
		  value: "bar"