baseurl: /edb-test
permalink: pretty
markdown: rdiscount
prose:
  # rooturl: "_posts"
  siteurl: 'http://prose.io/#mklarmann/edb-test/'
  ignore:
    # - _prose.yml
  metadata:
    _posts:
      - name: "@MODID"
        field:
          element: "text"
          label: "@MOID"